### ISSUE TITLE
Split configure from make

### ISSUE THREAD

**Issue by Gcenx** [dasmy/macos-crossover-cloud-build#5]
To make it simpler to found configure related issues it would be nicer to have this stage separated as I’ve done for the wine-staging workflow.

**Comment by dasmy** [comment]
True, I'll take care of this.

**Comment by dasmy** [comment]
Done with introducing https://github.com/dasmy/macos-crossover-cloud-build/blob/main/.github/workflows/build_monolithic.yml .
