### ISSUE TITLE
Wine32on64 LDFLAGS

### ISSUE THREAD

**Issue by Gcenx** [dasmy/macos-crossover-cloud-build#6]
https://github.com/dasmy/macos-crossover-cloud-build/blob/bb3c6797ddc0cd2b2dc035567638b4e8a2c7a692/.github/workflows/build_monolithic.yml#L244

I wouldn’t do that for 32on64, unless you need to make use of XQuartz copys of libfreetype/libpng for some reason.

You can just remove this line entirely for 32on64 slice.

**Comment by dasmy** [comment]
Done with https://github.com/dasmy/macos-crossover-cloud-build/commit/118824b57b376f7c98c6dbcf77ec52d8eabe63db
