### ISSUE TITLE
Configure not detecting some dependencies 

### ISSUE THREAD

**Issue by Gcenx** [dasmy/macos-crossover-cloud-build#8]
libsdl2 is used for controller support so it’s very important. I did submit a patch for this very issue to upstream wine. You could adapt that patch to CX sources or do what you did for PNG.

libMoltenVK is also not being detected, honestly not super important as the version provided by brew won’t work with DXVK anyway.

What I find weird is libpng and libMoltenVK are both detected correctly in the wine-staging workflow but not here as I don’t remember this being an issue.

**Comment by dasmy** [comment]
About libsdl2: Do you mean this commit: https://github.com/wine-mirror/wine/commit/e4fbae832c868e9fcf5a91c58255fe3f4ea1cb30 ?

Shouldn't I first `brew install sdl2` to see if is detected then or does macOS come with its own version?

**Comment by dasmy** [comment]
> libMoltenVK is also not being detected, honestly not super important as the version provided by brew won’t work with DXVK anyway.

All these difficulties and incompatibilities are driving me crazy... :-D

**Comment by Gcenx** [comment]
> About libsdl2: Do you mean this commit: [wine-mirror/wine@e4fbae8](https://github.com/wine-mirror/wine/commit/e4fbae832c868e9fcf5a91c58255fe3f4ea1cb30) ?

Yes that commit.

> Shouldn't I first `brew install sdl2` to see if is detected then or does macOS come with its own version?

If you go over the dependencies you will see brew installs libsdl2 as a dependence of FAudio. I’d also skipped dependencies that I know the GitHub images already contains.

> All these difficulties and incompatibilities are driving me crazy... :-D

Welcome to wine on MacOS

**Comment by Gcenx** [comment]
Add the following to configure for wine64

```
ac_cv_lib_soname_MoltenVK=$(brew --prefix molten-vk)/lib/libMoltenVK.dylib
```

If I’m correct that will resolve that issue, but as this is brew I’m not entirely sure.

**Comment by Gcenx** [comment]
The remaining deps configure is crying about after libMoltenVK aren’t of any real concern.

quicktime framework was removed in 10.12.SDK as that was 32Bit only, there’s an upstream patch that adds ` -without-quicktime` Here’s the commit https://github.com/wine-mirror/wine/commit/b99ec04f557fad83b89be406cbc605f09fdcc18a

libsane as explained is for scanners.

libgphoto2 are both about digital camera support.

libgsm isn’t compatible with 32on64.

VKD3D can also be ignored since that’s DirectX12 support and currently MoltenVK doesn’t implement enough of the Vulkan API to even handle the lowest level of support, in later versions of wine the VKD3D shader compiler will be used for the WineD3D Vulkan backend but still isn’t much use yet.

**Comment by dasmy** [comment]
Commmits
https://github.com/dasmy/macos-crossover-cloud-build/commit/e446627f2b32d21a4b2a2c2d250256c2854fc1b9 and
https://github.com/dasmy/macos-crossover-cloud-build/commit/88f58bfbfd4bdb22f3f5edd43d05f068c989959c
should fix detection of gphoto2 and sane (although I am personally not too interested in them).

Will wait until the build gets through before closing here.

**Comment by dasmy** [comment]
Dependency detection looks OK now.
